version: '3'

services:
  postgresql:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev
#  splitexpenses:
#    image: 'splitexpenses'
#    ports:
#      - '8080:8080'
#    environment:
#      - PORT=8080