# Generated by Django 3.0.8 on 2020-10-02 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('person', '0009_auto_20201002_1605'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='to',
        ),
        migrations.AddField(
            model_name='expense',
            name='too',
            field=models.ManyToManyField(related_name='to', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
    ]
