# Generated by Django 3.0.8 on 2020-10-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('expense', '0002_auto_20201002_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
    ]
