# Generated by Django 3.0.8 on 2020-10-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('person', '0012_auto_20201003_0710'),
        ('expense', '0004_auto_20201003_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to='person.Person'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='too',
            field=models.ManyToManyField(related_name='expenses', to='person.Person'),
        ),
    ]
